apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebspv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-12345678  # Replace with your actual volume ID
	fsType: ext4