---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myebspv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  awsElasticBlockStore:
    volumeID: vol-0c37922c4c209b3bd
    fsType: ext4