---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: DevOpsHangout
  labels:
    app: dev
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: DevOpsHangout
          image: nginx:1.7.9
          ports:
            - containerPort: 80
