apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: dev
spec:
  hard:
    pods: "5"                       # Maximum number of pods
    requests.cpu: "1"                # Total CPU requests
    requests.memory: "1Gi"           # Total memory requests
    limits.cpu: "2"                  # Total CPU limits
    limits.memory: "2Gi"            # Total memory limits
    configmaps: "5"                 # Maximum number of ConfigMaps
    services: "5"                    # Maximum number of services
    secrets: "5"                    # Maximum number of secrets
    persistentvolumeclaims: "5"     # Maximum number of persistent volume claims
    persistentvolumes: "5"          # Maximum number of persistent volumes (optional, usually managed by the cluster)