---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
spec:
  replicas: 6
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - dev
          - uat
          - qa
          - prod
  template:
    metadata:
      name: nginx
      labels:
        app: dev
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80

