---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          startupProbe:
            exec:
              command:
                - cat
                - /usr/share/nginx/html/index.html
            failureThreshold: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - cat
                - /usr/share/nginx/html/index.html
            initialDelaySeconds: 10
            periodSeconds: 10
            timeOutSeconds: 4
            failureThreshold: 2
            successThreshold: 1
          livenessProbe:
            exec:
              command:
                - cat
                - /usr/share/nginx/html/index.html
            initialDelaySeconds: 10
            periodSeconds: 10
            timeOutSeconds: 4
            failureThreshold: 6
            successThreshold: 1
