apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      nodeSelector:
        disktype: ssd
		app:prod
      containers:
      - name: example-container
        image: nginx
        ports:
        - containerPort: 80